# Generated by Django 3.1.7 on 2021-03-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsdb',
            name='email',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='adminsdb',
            name='lastname',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='adminsdb',
            name='password',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='adminsdb',
            name='phone',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='adminsdb',
            name='username',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AlterField(
            model_name='adminsdb',
            name='firstname',
            field=models.CharField(default='Type here', max_length=30),
        ),
    ]
