# Generated by Django 3.1.7 on 2021-03-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_auto_20210323_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='addpreregdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Type here', max_length=30)),
                ('lastname', models.CharField(default='Type here', max_length=30)),
                ('email', models.CharField(default='Type here', max_length=30)),
                ('phone', models.CharField(default='Type here', max_length=30)),
                ('date', models.CharField(default='Type here', max_length=30)),
                ('time', models.CharField(default='Type here', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='adminsdb',
            name='address',
            field=models.CharField(default='Type here', max_length=30),
        ),
    ]
