# Generated by Django 3.1.7 on 2021-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_auto_20210323_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='addvisitorsdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Type here', max_length=30)),
                ('lastname', models.CharField(default='Type here', max_length=30)),
                ('email', models.CharField(default='Type here', max_length=30)),
                ('phone', models.CharField(default='Type here', max_length=30)),
                ('companyname', models.CharField(default='Type here', max_length=30)),
                ('idnumber', models.CharField(default='Type here', max_length=30)),
            ],
        ),
    ]
