# Generated by Django 3.1.7 on 2021-03-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_addrolesdb'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addpreregdb',
            table='addpreregform',
        ),
    ]
