# Generated by Django 3.1.7 on 2021-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_auto_20210325_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpreregdb',
            name='address',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='addpreregdb',
            name='comment',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='addpreregdb',
            name='emp',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='addpreregdb',
            name='gender',
            field=models.CharField(default='Type here', max_length=30),
        ),
    ]
