# Generated by Django 3.1.7 on 2021-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_auto_20210325_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvisitorsdb',
            name='address',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='addvisitorsdb',
            name='emp',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='addvisitorsdb',
            name='gender',
            field=models.CharField(default='Type here', max_length=30),
        ),
        migrations.AddField(
            model_name='addvisitorsdb',
            name='purpose',
            field=models.CharField(default='Type here', max_length=30),
        ),
    ]
