# Generated by Django 3.1.7 on 2021-03-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_auto_20210325_2011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addvisitorsdb',
            table='addvisitorform',
        ),
    ]
