# Generated by Django 3.1.7 on 2021-03-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_auto_20210325_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvisitorsdb',
            old_name='firstname',
            new_name='fname',
        ),
    ]
