# Generated by Django 3.1.7 on 2021-03-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_auto_20210325_2032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addvisitorsdb',
            table=None,
        ),
    ]
