# Generated by Django 3.1.7 on 2021-03-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_auto_20210325_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersignupdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Type here', max_length=30)),
                ('email', models.CharField(default='Type here', max_length=30)),
                ('username', models.CharField(default='Type here', max_length=30)),
                ('password', models.CharField(default='Type here', max_length=30)),
            ],
        ),
    ]
