# Generated by Django 3.1.7 on 2021-03-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_usersignupdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvisitorsdb',
            old_name='fname',
            new_name='firstname',
        ),
    ]
